### ISSUE TITLE
calendar.setWeeklyCaptionProvider and calendar header don't map

### ISSUE THREAD

**Issue by ghost** [blackbluegl/calendar-component#11]
When i set start_date and end_date of a week form MONDAY to SUNDAY,
The header of calendar is not map to date.
It is from SUNDAY to SATURDAY .

Please see attached file.
![calendar_header](https://user-images.githubusercontent.com/30718314/29307707-24b3b1ca-81cd-11e7-9eee-28fef2c4024d.png)

**Comment by blackbluegl** [comment]
Have set the zone correctly? You can set the zone manually with calenar.setZoneId.

**Comment by ghost** [comment]
Yes, I set zone of Japan and default first day of week is SUNDAY, But i want to display first day of week is  MONDAY. So I set start_date and end_date of a week form MONDAY to SUNDAY, but it don't appear as i expected. 

In version 1, there is a method [setFirstDayOfWeek] to change firstDayOfWeek state of CalendarState, but in version 2, it removed. I think you should keep this method.

**Comment by blackbluegl** [comment]
yes, setFirstDayOfWeek is currently removed. :-/ 
i bring it back soon as possible.

**Comment by blackbluegl** [comment]
I have fixed it. Can you check it out? setFirstDayOfWeek is'nt necessary anymore. All you need is set start date to an sunday.

look at the demo source as example.
