### ISSUE TITLE
Some issues found

### ISSUE THREAD

**Issue by ns1045** [blackbluegl/calendar-component#13]
~~1. height is fix, not matter set sizeFull or a larger height.~~ <- this was my fault, the old style fixed the size...
~~2. rows are only rendered on today~~
<img width="1273" alt="strangerenderingcalendar" src="https://user-images.githubusercontent.com/16956482/30080919-aa1c8706-9285-11e7-9778-227cc3ba9bfe.png"> <-- another style error
3. header column local is rendering dayname correctly but date format is not corresponding to locals one. See previous screenshot
4. ~~style for calendar items does not work~~ it does

**Comment by blackbluegl** [comment]
i need more informations to reproduce this issue. OS, Browser, Versions. A test-case wich produce this behavior.

**Comment by ns1045** [comment]
OS: Mac OS 10.12.6
Browser: Firefox 55.0.3, Safari, chrome 

I will provide a testcase this evening...

Cheers 
Ns1045


------------------------------------------
Jens Boeckel
ABACUS Research AG
Software-Engineer

Von meinem iPhone gesendet

**Comment by ns1045** [comment]
@Override
  protected void init(@Nonnull final VaadinRequest vaadinRequest) {
    VerticalLayout mainLayout = new VerticalLayout();
    HorizontalLayout titleBar = new HorizontalLayout();
    HorizontalLayout navContentContainer = new HorizontalLayout();
    HorizontalLayout footer = new HorizontalLayout();

    mainLayout.addComponents(titleBar, navContentContainer, footer);

    mainLayout.setSizeFull();
    titleBar.setHeight(45, Unit.PIXELS);
    titleBar.setWidth(100, Unit.PERCENTAGE);
    footer.setHeight(30, Unit.PIXELS);
    footer.setWidth(100, Unit.PERCENTAGE);

    VerticalLayout navContainer = new VerticalLayout();
    navContainer.setWidth(200, Unit.PIXELS);
    navContainer.setHeight(100, Unit.PERCENTAGE);
    navContainer.addComponent(new InlineDateTimeField());
    navContainer.addComponent(new InlineDateTimeField());

    Calendar<BasicItem> calendar = new Calendar<>("Calendar", new BasicItemProvider<>());
    calendar.setSizeFull();
    LocalDate startDay = LocalDate.now();
    if (startDay.getDayOfWeek().getValue() == 0) {
      startDay = startDay.plusDays(1L);
    } else if (startDay.getDayOfWeek().getValue() > 1) {
      startDay = startDay.minusDays(startDay.getDayOfWeek().getValue() - 1);
    }
    calendar.setStartDate(startDay.atStartOfDay(ZoneId.systemDefault()));
    calendar.setEndDate(startDay.plusDays(5L).atStartOfDay(ZoneId.systemDefault()));
    calendar.setFirstVisibleHourOfDay(6);
    calendar.setLastVisibleHourOfDay(20);
    calendar.setLocale(Locale.GERMAN);

    HorizontalLayout calendarContainer = new HorizontalLayout();
    calendarContainer.setSizeFull();
    calendarContainer.addComponent(calendar);

    navContentContainer.addComponent(navContainer);
    navContentContainer.addComponent(calendarContainer);
    navContentContainer.setExpandRatio(calendarContainer, 1);
    navContentContainer.setSizeFull();

    mainLayout.setExpandRatio(navContentContainer, 1);

    setContent(mainLayout);
  }

**Comment by blackbluegl** [comment]
To fix this you can set a CaptionProvider for the first time. I have fixed this for the next release.

calendar.setWeeklyCaptionProvider(date -> DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM).withLocale(getLocale()).format(date));

**Comment by blackbluegl** [comment]
Version 2.0-Beta3

**Comment by ns1045** [comment]
It works with Version 2.0-Beta3. Great! thanks.

**Comment by ns1045** [comment]
I would wonder why the visibility of the methods setFirstVisibilityHourOfDay und setLastVisibilityHourOfDay was reduced from public to private between beta2 and beta3?

**Comment by blackbluegl** [comment]
there are new methods for that:
withVisibleHours
withVisibleDays
