### ISSUE TITLE
BasicBackwardHandler Daily Mode Problem

### ISSUE THREAD

**Issue by aorsorlu** [blackbluegl/calendar-component#17]
In BasicBackwardHandler class there is a bug in finding previous day in daily mode (Same bug exists in BasicForwardHandler). If not showing weekends on calendar (getFirstVisibleDayOfWeek => 1, getLastVisibleDayOfWeek => 5), when you press back button on Monday (i expect to see previous friday) there is a bug at line :
`dayOfWeek = start.get(ChronoField.DAY_OF_WEEK);`
It has to be:
`dayOfWeek = newDate.get(ChronoField.DAY_OF_WEEK);`

**Comment by blackbluegl** [comment]
Fixed in next release
