### ISSUE TITLE
Calendar Days not Responding to Locale Changes?

### ISSUE THREAD

**Issue by bshue** [blackbluegl/calendar-component#19]
Hello,

First, thank you for working on a Calendar add-on for Vaadin. The framework most certainly needs a calendar.

I cannot figure out how to change the order of the days in the Calendar. The default order is:

Mon, Tue, Wed, Thu, Fri, Sat, Sun

but this does not match the typical US calendar. I want the days to be in the following order:

Sun, Mon, Tue, Wed, Thu, Fri, Sat

Code example:

calendar = new Calendar<>(eventProvider);
calendar.setLocale(Locale.ENGLISH);
calendar.markAsDirty();

Thank you for your time!

**Comment by pwilkin** [comment]
This might be due to not respecting `WeekFields.of(locale).getFirstDayOfWeek()`

**Comment by blackbluegl** [comment]
Fixed in next release.

**Comment by blackbluegl** [comment]
not completly fixed :-/

**Comment by blackbluegl** [comment]
works in a range of a full week.
