### ISSUE TITLE
Set the Calender with MonthMode at the Beginning

### ISSUE THREAD

**Issue by Amutheezan** [blackbluegl/calendar-component#21]
How to keep the Monthly Mode Active in Beginning and When Click A Date, which trigger DateClickEvent and Not to Go Into Specific Date

**Comment by Vilkaz** [comment]
To set Monthly mode you need something like this

`calendar.withMonth(ZonedDateTime.now().getMonth());`

just do that in initialisation.

**Comment by bladem** [comment]
only needs `calendar.withMonth(ZonedDateTime.now());`
It's gets the moth of actual day.

**Comment by blackbluegl** [comment]
calendar.withMonth(ZonedDateTime.now());
