### ISSUE TITLE
Switch off day and week view, change listener

### ISSUE THREAD

**Issue by katamlek** [blackbluegl/calendar-component#26]
Hi! As I’m pretty new to the calendar addon, I’d appreciate your help.

1. I want to switch off day and week calendar view, leaving only the monhly view. Do you guys happen to know how to do that? So far I managed to show monthly view as the defaul one.

2. I want to redirect to custom page when the user clicks a day in calendar. Also, any help appreciated!

Thanks in advance!

**Comment by blackbluegl** [comment]
Set an empty BasicDateClickHandler.

`calendar.setHandler((CalendarComponentEvents.DateClickHandler) e -> {});`
