### ISSUE TITLE
Isn't possible to set firstDayOfWeek 

### ISSUE THREAD

**Issue by voltor** [blackbluegl/calendar-component#27]
It is possible in the Calendar of Vaadin 7. Please, return this feature.

**Comment by lrozenblyum** [comment]
It's indeed a problem now - we cannot migrate to Vaadin8 due to this limitation.
We need setting first day of week independent of the locale which was possible in Vaadin7

**Comment by voltor** [comment]
The old issue for this feature: https://github.com/vaadin/framework/issues/7285

**Comment by blackbluegl** [comment]
merged. Thanks

**Comment by blackbluegl** [comment]
merged
