### ISSUE TITLE
SetHeight to 100% gives wrong height

### ISSUE THREAD

**Issue by evanzel** [blackbluegl/calendar-component#6]
When calendar.SetHeight is 100% it gives a bigger height than it should and the last row is usually cut off.
It is more apparent with bigger sizes.

To be fair, it is the same in Vaadin 7 and in Vaadin 8 compatibility packages.
See also open issue https://github.com/vaadin/framework/issues/8333

Apparently only in monthly View.

**Comment by blackbluegl** [comment]
separate issue created ;-) for the second one

**Comment by blackbluegl** [comment]
fixed!
next release

**Comment by BrianSiimAndersenEG** [comment]
I'm experiencing this problem in beta 3 when I set the calendar to full size (setSizeFull). The bottom of the calendar month view is cut off - the week and day calendars are fine. Shouldn't this have been fixed en beta 3?

**Comment by TorstenBMR** [comment]
still found this in BETA4 - any chance to get this fixed?
