### ISSUE TITLE
Calendar Component for Vaadin 8 - Change Month Title when selecting next month date

### ISSUE THREAD

**Issue by DabhiGhanshyam** [blackbluegl/calendar-component#8]
In Calendar Component for Vaadin 8 in Calendar Add on,  Is there any upcoming feature to navigate Next Month Or  Last Month and by selecting date of September month then Month label changes accordingly?

**Comment by blackbluegl** [comment]
Version 2.0-Beta2

**Comment by DabhiGhanshyam** [comment]
Okay Thanks, Surely I'll take look at 2.0-Beta2.
